# Railway Deployment Configuration - DashDice Unified Backend
# Deploys single Go backend service handling all matchmaking

[build]
builder = "dockerfile"

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ENVIRONMENT = "production"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3