# Railway Deployment Configuration - DashDice Unified Backend
# Deploys single Go backend service handling all matchmaking

[build]
builder = "dockerfile"

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ENVIRONMENT = "production"
FIREBASE_PROJECT_ID = "dashdice-d1b86"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@dashdice-d1b86.iam.gserviceaccount.com"
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/jTIZt3VDuiLA\nMLh6iexsRoSKfSl1CCqDjmfrTg98LauANayY/ai7Ot/ggsBtYlJxqwjp1bgpGDMD\nxtiWZwGLZdgO6FKwae623h4hqGmEq+/mpV6ypjItlCqck3l5HgmSid//9I3FcvRD\nrr2F5jnewjlkpxyVIunVOf8lbnVLompql82Qudt8Hcbho/snfzrRzvBaLJPxDEjY\nzTC70Cvjy23QoEUjw6Mt6saFgCTKOchuc0yP8PpG0UCNz+25pzCBc4BewIblnAFd\nda1RKQOzcBwy6WkhDhtezMqQN5A3M+Z2DIZKPAT+Q0bE9vfAI2Qy+wcKxXjDWHJf\nyfcHVSPBAgMBAAECggEAI6KAz4fxqMfX7ykhKKq/8OStg5YFQGBkiFTVwFClUNSu\nMwvJMC0AVtR9EadBZRgFfl/zKI051WtLEkjLwi8nemdX6m4N9APBBQQNVvWdq7DQ\n0HezRkjkzNXjl31X+9A6t6guo887EKByEKVRXLeXzHkVdEQibRwxpBlF/hCugYND\nEGESR3G2n01D61JZ9VghBXEbZhYY+k6MyB803g0i59hJU3D+wNW2l4LUkDJRCTwd\n690JAfzdA8vdUk6xdni09Cu7fbWxpugMCwBTSjM5SvcpTM5ghdYPAX0HS8Aj4B7e\nY295lZO4Lx1suH6zgzxVcr2/KKX3iOxvXnHy3HiOAQKBgQDnSW+WTAcCB6cgV+2G\n5kDpg6B4NTnaSg95k6ddlOUm0rJPznbFn5sNnuyUNaA7gDxM9XHQY5tsfXvWVGKn\nDez/8ci8B5ZlQodEPogDtCNUHfAdK2C7bWxOb93MQZUerfyjOxT5KbcdQ69+16Uq\n+3v5TF26Xys49PEEoI+hU7qOZQKBgQDUBNmLwD9SCuQa72BWh2oxxr7p4g+jInZH\nESiTYKkm5NpEu7rr/gR7E3+fb09sZ/NA2TIYwAhN8MpOCs/38ryjMD2Wc7I1MajV\nlO0GyedgVf6QFHmd0rzpVM/mmxOrULehQA0de57SKwFkBfDKtjYEc/xV8V/J6IZ/\nqQbn4GHsLQKBgAxYRRZ2lGEtW2REjS8IFyrfla8U2DOohE7u7J34FosN7+qGkJxX\nuoTtmJ8IhbbnT1CkQSDoUCFoSTXVZzaXbbDzjM1McmCRPnsMA2J/OOuCdZB5Aj6+\nxmshWWtPjNAIZVWpD6OE8HslY7aXd/9lUOarhs0tyzbNDBg9Ia1wtKJpAoGBAJUX\ny/uQd3a0HfArAS4YD79tKXfC9ogbhd033ba1tH2bVTocYbfuayw5a/esCMgM2Wxy\nz93DvJNCjqEOzWxpD+oZ1FVmip0JjNaU4ZFyjfiawGaFX3hyZ1IVyBU8XDqOinMk\nXZSsB+V3RIUYAFoshBPhlELDeD69+0buj+KjUXkJAoGAJov/4Q5bo48iD8eE0zIj\nenMy6PJbcXk+zEb+9wfWsnB0rEvli0+/IDm03ccsQfatan5BzfnhZYw5w1XzZl/F\nVSfixxwdQB8nyfnwgxfob7oEivaeb7tzXZyE7VRK1HkK2RHLFDIto4+3+FZkyprt\nVaSunagBr19MhxVlcAv4rhY=\n-----END PRIVATE KEY-----"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3