# Railway Deployment Configuration - DashDice Unified Backend
# Deploys single Go backend service handling all matchmaking

[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildCommand = "cd backend && docker build -t dashdice-backend ."

[deploy]
startCommand = "cd backend && ./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ENVIRONMENT = "production"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3