# AlertManager Configuration for DashDice
# Comprehensive alerting rules and notification channels

global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: 'alerts@dashdice.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Templates for alert messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 15m

    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_interval: 30s
      repeat_interval: 4h

    # System alerts
    - match:
        category: system
      receiver: 'system-alerts'

    # Application alerts
    - match:
        category: application
      receiver: 'application-alerts'

    # Business alerts
    - match:
        category: business
      receiver: 'business-alerts'

# Inhibit rules to prevent alert spam
inhibit_rules:
  # Inhibit warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit specific service warnings if general service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service']

# Notification receivers
receivers:
  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@dashdice.com'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} on {{ .GroupLabels.instance }}'
        body: |
          Critical alert fired:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

    slack_configs:
      - channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true

    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: 'Critical alert: {{ .GroupLabels.alertname }}'

  # Warning alerts
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

  # System alerts
  - name: 'system-alerts'
    email_configs:
      - to: 'devops@dashdice.com'
        subject: '🖥️ System Alert: {{ .GroupLabels.alertname }}'
        body: |
          System alert details:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Host: {{ .Labels.instance }}
          Description: {{ .Annotations.description }}
          {{ end }}

    slack_configs:
      - channel: '#system-monitoring'
        title: '🖥️ System Alert: {{ .GroupLabels.alertname }}'

  # Application alerts
  - name: 'application-alerts'
    slack_configs:
      - channel: '#app-monitoring'
        title: '🔧 Application Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Business alerts
  - name: 'business-alerts'
    email_configs:
      - to: 'business@dashdice.com'
        subject: '📊 Business Metric Alert: {{ .GroupLabels.alertname }}'

    slack_configs:
      - channel: '#business-metrics'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'

# Alert grouping configuration
time_intervals:
  # Business hours (9 AM to 6 PM, Monday to Friday)
  - name: business-hours
    time_intervals:
      - times:
        - start_time: '09:00'
          end_time: '18:00'
        weekdays: ['monday:friday']

  # Off-hours and weekends
  - name: off-hours
    time_intervals:
      - times:
        - start_time: '18:00'
          end_time: '09:00'
        weekdays: ['monday:friday']
      - weekdays: ['saturday', 'sunday']

# Mute configuration for maintenance windows
mute_time_intervals:
  # Planned maintenance window
  - name: maintenance-window
    time_intervals:
      - times:
        - start_time: '02:00'
          end_time: '04:00'
        weekdays: ['sunday']
