[build]
builder = "docker"
buildCommand = "docker build -t dashdice-api ."

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = [
  "PORT=8080"
]
